<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DesktopBoxes.Core\DesktopBoxes.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vanara.PInvoke.User32" Version="5.0.7" />
    <PackageReference Include="Vanara.Windows.Shell" Version="5.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
