<Project>
  <PropertyGroup>
    <Authors>DesktopBoxes contributors</Authors>
    <Copyright>Copyright © 2026 DesktopBoxes contributors</Copyright>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Deterministic>true</Deterministic>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
